/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("edu.sc.seis.launch4j") version "3.0.5"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // MySQL Connector JAR dependency
    implementation("com.mysql:mysql-connector-j:8.4.0")

    // FlatLaf for modern Swing look and feel
    implementation("com.formdev:flatlaf:3.4.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "MainSystem.Main"
}

// Add this configuration anywhere in the file
launch4j {
    mainClassName.set("MainSystem.Main") // Your Swing entry point
    outfile.set("Project3App.exe")       // Name of the output launcher
    headerType.set("gui")                // "gui" ensures no black command prompt opens
    
    // Optional: Add an icon
    // icon.set("${project.projectDir}/src/main/resources/Icons/favicon.ico")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
