/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrameSystem.SLibrary.SComponents;

import java.awt.Dimension;
import java.beans.BeanProperty;
import java.util.ArrayList;

/**
 *
 * @author SPPR-LOQ
 */
public class STable extends SPanel{

    private ArrayList<SPanel> rows;
    private int rowHeight = 60; // Default height
    
    /**
     * Creates new form STable
     */
    public STable(){
        initComponents();
    }

// ==== Getters and Setters ==================================================================================

    /**
     * Adds a row to the table and automatically resizes the container.
     */
    public void addRow(SPanel rowComponent) {
        rows.add(rowComponent);
        container.add(rowComponent);
        resizeTable();
    }

    /**
     * Clears all rows from the table.
     */
    public void clearRows() {
        rows.clear();
        container.removeAll();
        resizeTable();
    }

    /**
     * Automatically calculates the height based on row count and row height.
     */
    public void resizeTable() {
        int height = (rows.size() * rowHeight) + 10;
        
        // Automatically resize the container based on its contents
        container.setPreferredSize(new Dimension(container.getWidth(), height));
        
        container.revalidate();
        container.repaint();
    }

    public ArrayList<SPanel> getRows() {
        return rows;
    }
    
    public SScrollPane getScrollPane() {
        return scrollPane;
    }
    
// -----------------------------------------------------------------------------------------------------------
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "")
    public void setRowHeight(int rowHeight) {
        this.rowHeight = rowHeight;
    }

    public int getRowHeight(){
        return rowHeight;
    }
    
// ==== Overrided Methods ====================================================================================
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new FrameSystem.SLibrary.SComponents.SScrollPane();
        container = new FrameSystem.SLibrary.SComponents.SPanel();

        setPaintBackground(false);
        setLayout(new java.awt.BorderLayout());

        container.setPaintBackground(false);
        container.setLayout(new javax.swing.BoxLayout(container, javax.swing.BoxLayout.Y_AXIS));
        scrollPane.setViewportView(container);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FrameSystem.SLibrary.SComponents.SPanel container;
    private FrameSystem.SLibrary.SComponents.SScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
