package FrameSystem.SLibrary.SComponents;

import java.awt.Color;
import java.awt.Dimension;
import java.beans.BeanProperty;
import java.util.ArrayList;
import javax.swing.JComponent;

public class STable extends SPanel{

    private ArrayList<SPanel> rows = new ArrayList<>();
    private int rowHeight = 60; 
    
    public STable(){
        initComponents();
        scrollPane.getViewport().setOpaque(false);
    }

// ==== Getters and Setters ==================================================================================

    public void addComponent(JComponent component){
        container.add(component);
        component.addMouseListener(scrollPane.getListener());
        resizeTable();
    }
    
    public void addRow(SPanel rowComponent) {
        rows.add(rowComponent);
        container.add(rowComponent);
        rowComponent.addInnerListeners(scrollPane.getListener());
        resizeTable();
    }

    public void clearRows() {
        rows.clear();
        container.removeAll();
        resizeTable();
    }

    public void resizeTable() {
        int height = (rows.size() * rowHeight);
        
        container.setPreferredSize(new Dimension(0, height));
        
        container.revalidate();
        container.repaint();
    }

    public ArrayList<SPanel> getRows() {
        return rows;
    }
    
    public SScrollPane getScrollPane() {
        return scrollPane;
    }
    
// ==== STable Properties ====================================================================================
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "")
    public void setRowHeight(int rowHeight) {
        this.rowHeight = rowHeight;
    }

    public int getRowHeight(){
        return rowHeight;
    }
    
    private int blockIncrement = 60; 

    @BeanProperty(preferred = true, description = "Sets the block scroll speed (when clicking the scrollbar track)")
    public void setBlockIncrement(int blockIncrement) {
        this.blockIncrement = blockIncrement;
        container.setBlockIncrement(blockIncrement);
    }

    public int getBlockIncrement() {
        return blockIncrement;
    }

// ==== ScrollPane Delegated Properties ======================================================================

    @BeanProperty(preferred = true, visualUpdate = true, description = "The background color of the scrollbar track")
    public void setScrollbarBackgroundColor(Color color) {
        scrollPane.setScrollbarBackgroundColor(color);
    }

    public Color getScrollbarBackgroundColor() {
        return scrollPane.getScrollbarBackgroundColor();
    }

    @BeanProperty(preferred = true, visualUpdate = true, description = "The default color of the scrollbar thumb")
    public void setScrollbarColor(Color color) {
        scrollPane.setScrollbarColor(color);
    }

    public Color getScrollbarColor() {
        return scrollPane.getScrollbarColor();
    }

    @BeanProperty(preferred = true, visualUpdate = true, description = "The hover color of the scrollbar thumb")
    public void setScrollbarHoverColor(Color color) {
        scrollPane.setHoverColor(color);
    }

    public Color getScrollbarHoverColor() {
        return scrollPane.getHoverColor();
    }
    
// ==== Overrided Methods ====================================================================================
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new FrameSystem.SLibrary.SComponents.SScrollPane();
        container = new FrameSystem.SLibrary.SComponents.ScrollableSPanel();

        setPaintBackground(false);

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setHoverColor(new java.awt.Color(73, 73, 73));
        scrollPane.setScrollbarBackgroundColor(new java.awt.Color(255, 255, 255));
        scrollPane.setScrollbarColor(new java.awt.Color(229, 229, 229));
        scrollPane.setOpaque(false);

        container.setPaintBackground(false);
        container.setLayout(new javax.swing.BoxLayout(container, javax.swing.BoxLayout.Y_AXIS));
        scrollPane.setViewportView(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FrameSystem.SLibrary.SComponents.ScrollableSPanel container;
    private FrameSystem.SLibrary.SComponents.SScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
