/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrameSystem.SLibrary.SComponents;

import java.awt.Dimension;
import java.beans.BeanProperty;
import java.util.ArrayList;
import javax.swing.JComponent;

/**
 *
 * @author SPPR-LOQ
 */
public class STable extends SPanel{

    private ArrayList<SPanel> rows = new ArrayList<>();
    private int rowHeight = 60; // Default height
    
    /**
     * Creates new form STable
     */
    public STable(){
        initComponents();
        scrollPane.getViewport().setOpaque(false);
    }

// ==== Getters and Setters ==================================================================================

    public void addComponent(JComponent component){
        container.add(component);
        component.addMouseListener(scrollPane.getListener());
        resizeTable();
    }
    
    /**
     * Adds a row to the table and automatically resizes the container.
     * @param rowComponent
     */
    public void addRow(SPanel rowComponent) {
        rows.add(rowComponent);
        container.add(rowComponent);
        rowComponent.addInnerListeners(scrollPane.getListener());
        resizeTable();
    }

    /**
     * Clears all rows from the table.
     */
    public void clearRows() {
        rows.clear();
        container.removeAll();
        resizeTable();
    }

    /**
     * Automatically calculates the height based on row count and row height.
     */
    public void resizeTable() {
        int height = (rows.size() * rowHeight);
        
        // We can pass 0 for the width because getScrollableTracksViewportWidth() overrides it anyway!
        container.setPreferredSize(new Dimension(0, height));
        
        container.revalidate();
        container.repaint();
    }

    public ArrayList<SPanel> getRows() {
        return rows;
    }
    
    public SScrollPane getScrollPane() {
        return scrollPane;
    }
    
// -----------------------------------------------------------------------------------------------------------
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "")
    public void setRowHeight(int rowHeight) {
        this.rowHeight = rowHeight;
    }

    public int getRowHeight(){
        return rowHeight;
    }
    
    private int blockIncrement = 60; 

    @BeanProperty(preferred = true, description = "Sets the block scroll speed (when clicking the scrollbar track)")
    public void setBlockIncrement(int blockIncrement) {
        this.blockIncrement = blockIncrement;
        container.setBlockIncrement(blockIncrement);
    }

    public int getBlockIncrement() {
        return blockIncrement;
    }
    
// ==== Overrided Methods ====================================================================================
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new FrameSystem.SLibrary.SComponents.SScrollPane();
        container = new FrameSystem.SLibrary.SComponents.ScrollableSPanel();

        setPaintBackground(false);

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setHoverColor(new java.awt.Color(73, 73, 73));
        scrollPane.setScrollbarBackgroundColor(new java.awt.Color(255, 255, 255));
        scrollPane.setScrollbarColor(new java.awt.Color(229, 229, 229));
        scrollPane.setOpaque(false);

        container.setPaintBackground(false);
        container.setLayout(new javax.swing.BoxLayout(container, javax.swing.BoxLayout.Y_AXIS));
        scrollPane.setViewportView(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FrameSystem.SLibrary.SComponents.ScrollableSPanel container;
    private FrameSystem.SLibrary.SComponents.SScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
