/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrameSystem.LayerFolder_Main.Layers.LayerFolder_Home.Module;

import FrameSystem.SLibrary.SComponents.SPanel;

/**
 *
 * @author SPPR-LOQ
 */
public class ModuleHome extends SPanel{

    /**
     * Creates new form ModuleHome
     */
    public ModuleHome(){
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane_Main = new javax.swing.JLayeredPane();
        layerHome1 = new FrameSystem.LayerFolder_Main.Layers.LayerFolder_Home.Layers.LayerHome();
        sPanelMenu1 = new FrameSystem.LayerFolder_Main.Layers.LayerFolder_Home.Components.SPanelHomeMenu();
        sPanel1 = new FrameSystem.SLibrary.SComponents.SPanel();
        sLabel25 = new FrameSystem.SLibrary.SComponents.SLabel();
        sLabelHover1 = new FrameSystem.SLibrary.SComponents.SLabelHover();
        sPanel3 = new FrameSystem.SLibrary.SComponents.SPanel();
        sPanelMenu2 = new FrameSystem.LayerFolder_Main.Layers.LayerFolder_Home.Components.SPanelHomeMenu();
        sPanel2 = new FrameSystem.SLibrary.SComponents.SPanel();
        sLabel26 = new FrameSystem.SLibrary.SComponents.SLabel();
        sLabelHover2 = new FrameSystem.SLibrary.SComponents.SLabelHover();
        sPanel6 = new FrameSystem.SLibrary.SComponents.SPanel();

        layeredPane_Main.setLayout(new java.awt.CardLayout());

        layerHome1.setBackground(new java.awt.Color(255, 247, 247));
        layerHome1.setForeground(new java.awt.Color(239, 239, 239));

        javax.swing.GroupLayout layerHome1Layout = new javax.swing.GroupLayout(layerHome1);
        layerHome1.setLayout(layerHome1Layout);
        layerHome1Layout.setHorizontalGroup(
            layerHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        layerHome1Layout.setVerticalGroup(
            layerHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );

        layeredPane_Main.add(layerHome1, "card2");

        sPanelMenu1.setBackground(new java.awt.Color(255, 255, 255));
        sPanelMenu1.setBorderColor(new java.awt.Color(228, 228, 235));
        sPanelMenu1.setBorderLine(2);
        sPanelMenu1.setMaximumSize(new java.awt.Dimension(289, 32767));
        sPanelMenu1.setMinimumSize(new java.awt.Dimension(269, 100));
        sPanelMenu1.setPreferredSize(new java.awt.Dimension(269, 0));

        sPanel1.setBackground(new java.awt.Color(242, 242, 242));
        sPanel1.setRadius(15);
        sPanel1.setRounded(true);
        sPanel1.setPreferredSize(new java.awt.Dimension(229, 50));

        sLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Menu/mainLogo.png"))); // NOI18N

        javax.swing.GroupLayout sPanel1Layout = new javax.swing.GroupLayout(sPanel1);
        sPanel1.setLayout(sPanel1Layout);
        sPanel1Layout.setHorizontalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(sLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        sPanel1Layout.setVerticalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sLabelHover1.setDefaultColor(new java.awt.Color(242, 242, 242));
        sLabelHover1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sLabelHover1.setHoverColor(new java.awt.Color(229, 229, 229));
        sLabelHover1.setIconSize(12);
        sLabelHover1.setRadius(15);
        sLabelHover1.setScaledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Menu/collapse.png"))); // NOI18N
        sLabelHover1.setMaximumSize(new java.awt.Dimension(29, 50));
        sLabelHover1.setMinimumSize(new java.awt.Dimension(29, 50));
        sLabelHover1.setPreferredSize(new java.awt.Dimension(29, 50));

        sPanel3.setBackground(new java.awt.Color(228, 228, 235));
        sPanel3.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout sPanel3Layout = new javax.swing.GroupLayout(sPanel3);
        sPanel3.setLayout(sPanel3Layout);
        sPanel3Layout.setHorizontalGroup(
            sPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        sPanel3Layout.setVerticalGroup(
            sPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sPanelMenu1Layout = new javax.swing.GroupLayout(sPanelMenu1);
        sPanelMenu1.setLayout(sPanelMenu1Layout);
        sPanelMenu1Layout.setHorizontalGroup(
            sPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sPanelMenu1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(sPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addGroup(sPanelMenu1Layout.createSequentialGroup()
                        .addComponent(sPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(sLabelHover1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        sPanelMenu1Layout.setVerticalGroup(
            sPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanelMenu1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(sPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sLabelHover1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sPanelMenu2.setBackground(new java.awt.Color(255, 255, 255));
        sPanelMenu2.setBorderColor(new java.awt.Color(228, 228, 235));
        sPanelMenu2.setBorderLine(2);
        sPanelMenu2.setMinimumSize(new java.awt.Dimension(80, 100));
        sPanelMenu2.setPreferredSize(new java.awt.Dimension(80, 0));

        sPanel2.setBackground(new java.awt.Color(242, 242, 242));
        sPanel2.setRadius(15);
        sPanel2.setRounded(true);
        sPanel2.setPreferredSize(new java.awt.Dimension(50, 50));

        sLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Menu/mainLogoMinimized.png"))); // NOI18N

        javax.swing.GroupLayout sPanel2Layout = new javax.swing.GroupLayout(sPanel2);
        sPanel2.setLayout(sPanel2Layout);
        sPanel2Layout.setHorizontalGroup(
            sPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sPanel2Layout.setVerticalGroup(
            sPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sPanel2Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(sLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        sLabelHover2.setDefaultColor(new java.awt.Color(242, 242, 242));
        sLabelHover2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sLabelHover2.setHoverColor(new java.awt.Color(229, 229, 229));
        sLabelHover2.setIconSize(12);
        sLabelHover2.setRadius(15);
        sLabelHover2.setScaledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Menu/expand.png"))); // NOI18N
        sLabelHover2.setMaximumSize(new java.awt.Dimension(50, 29));
        sLabelHover2.setMinimumSize(new java.awt.Dimension(50, 29));
        sLabelHover2.setPreferredSize(new java.awt.Dimension(50, 29));

        sPanel6.setBackground(new java.awt.Color(228, 228, 235));
        sPanel6.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout sPanel6Layout = new javax.swing.GroupLayout(sPanel6);
        sPanel6.setLayout(sPanel6Layout);
        sPanel6Layout.setHorizontalGroup(
            sPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sPanel6Layout.setVerticalGroup(
            sPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sPanelMenu2Layout = new javax.swing.GroupLayout(sPanelMenu2);
        sPanelMenu2.setLayout(sPanelMenu2Layout);
        sPanelMenu2Layout.setHorizontalGroup(
            sPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sPanelMenu2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(sPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(sLabelHover2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        sPanelMenu2Layout.setVerticalGroup(
            sPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanelMenu2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(sPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sLabelHover2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sPanelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sPanelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(layeredPane_Main)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane_Main)
            .addComponent(sPanelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
            .addComponent(sPanelMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FrameSystem.LayerFolder_Main.Layers.LayerFolder_Home.Layers.LayerHome layerHome1;
    private javax.swing.JLayeredPane layeredPane_Main;
    private FrameSystem.SLibrary.SComponents.SLabel sLabel25;
    private FrameSystem.SLibrary.SComponents.SLabel sLabel26;
    private FrameSystem.SLibrary.SComponents.SLabelHover sLabelHover1;
    private FrameSystem.SLibrary.SComponents.SLabelHover sLabelHover2;
    private FrameSystem.SLibrary.SComponents.SPanel sPanel1;
    private FrameSystem.SLibrary.SComponents.SPanel sPanel2;
    private FrameSystem.SLibrary.SComponents.SPanel sPanel3;
    private FrameSystem.SLibrary.SComponents.SPanel sPanel4;
    private FrameSystem.SLibrary.SComponents.SPanel sPanel5;
    private FrameSystem.SLibrary.SComponents.SPanel sPanel6;
    private FrameSystem.LayerFolder_Main.Layers.LayerFolder_Home.Components.SPanelHomeMenu sPanelMenu1;
    private FrameSystem.LayerFolder_Main.Layers.LayerFolder_Home.Components.SPanelHomeMenu sPanelMenu2;
    // End of variables declaration//GEN-END:variables
}
