package FrameSystem.Layers.Units.Components;

import DatabaseSystem.UnitsData.UnitsDataOccupancy;
import DatabaseSystem.UnitsData.UnitsDataUnitStatus;
import FrameSystem.SLibrary.SComponents.SPanel;
import java.awt.Color;

public class ObjectUnitHighlight extends SPanel{

    public ObjectUnitHighlight(){
        initComponents();
    }
    
    public void setOccupancy(UnitsDataOccupancy occupancy){
        sLabel1.setText(occupancy.getStringName());
        
        Color bgColor = new Color(250, 250, 250);
        Color borderColor = new Color(230, 230, 230);
        Color textColor = new Color(70, 70, 70);
        
        switch(occupancy){
            case Null, Inventory -> {
                bgColor = new Color(241, 245, 249);
                borderColor = new Color(203, 213, 225);
                textColor = new Color(71, 85, 105);
            }
            case Owner, OwnerWeekenders, OwnerNoActivity -> {
                bgColor = new Color(239, 246, 255);
                borderColor = new Color(191, 219, 254);
                textColor = new Color(30, 64, 175);
            }
            case Tenant, TenantWeekenders, TenantNoActivity -> {
                bgColor = new Color(255, 247, 237);
                borderColor = new Color(254, 215, 170);
                textColor = new Color(154, 52, 18);
            }
            case UnturnedOver -> {
                bgColor = new Color(254, 242, 242);
                borderColor = new Color(254, 202, 202);
                textColor = new Color(153, 27, 27);
            }
        }
        
        sPanel1.setDefaultBackgroundColor(bgColor);
        sPanel1.setDefaultBorderColor(borderColor);
        sLabel1.setForeground(textColor);
        sPanel1.repaint();
    }
    
    public void setUnitStatus(UnitsDataUnitStatus unitStatus){
        sLabel1.setText(unitStatus.getStringName());
        
        Color dotColor = new Color(200, 200, 200);
        Color bgColor = new Color(250, 250, 250);
        Color borderColor = new Color(230, 230, 230);
        Color textColor = new Color(70, 70, 70);
        
        switch(unitStatus){
            case Null, Inventory -> {
                dotColor = new Color(148, 163, 184);
                bgColor = new Color(241, 245, 249);
                borderColor = new Color(203, 213, 225);
                textColor = new Color(71, 85, 105);
            }
            case TurnedOver -> {
                dotColor = new Color(74, 222, 128);
                bgColor = new Color(240, 253, 244);
                borderColor = new Color(134, 239, 172);
                textColor = new Color(22, 101, 52);
            }
            case UnturnedOver -> {
                dotColor = new Color(248, 113, 113);
                bgColor = new Color(254, 242, 242);
                borderColor = new Color(254, 202, 202);
                textColor = new Color(153, 27, 27);
            }
        }
        
        sPanel1.setDefaultBackgroundColor(bgColor);
        sPanel1.setDefaultBorderColor(borderColor);
        sLabel1.setForeground(textColor);
        sPanel1.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sPanel1 = new FrameSystem.SLibrary.SComponents.SPanel();
        sLabel1 = new FrameSystem.SLibrary.SComponents.SLabel();

        setPaintBackground(false);
        setMaximumSize(new java.awt.Dimension(90, 50));
        setMinimumSize(new java.awt.Dimension(90, 50));
        setPreferredSize(new java.awt.Dimension(90, 50));

        sPanel1.setBorderLine(2);
        sPanel1.setDefaultBackgroundColor(new java.awt.Color(250, 250, 250));
        sPanel1.setDefaultBorderColor(new java.awt.Color(230, 230, 230));
        sPanel1.setRadius(26);
        sPanel1.setRounded(true);

        sLabel1.setForeground(new java.awt.Color(70, 70, 70));
        sLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sLabel1.setText("Owner");

        javax.swing.GroupLayout sPanel1Layout = new javax.swing.GroupLayout(sPanel1);
        sPanel1.setLayout(sPanel1Layout);
        sPanel1Layout.setHorizontalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(sLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        sPanel1Layout.setVerticalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(sPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public FrameSystem.SLibrary.SComponents.SLabel sLabel1;
    public FrameSystem.SLibrary.SComponents.SPanel sPanel1;
    // End of variables declaration//GEN-END:variables
}
