/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrameSystem.Layers.Units.Components;

import DatabaseSystem.UnitsData.UnitsDataOccupancy;
import static DatabaseSystem.UnitsData.UnitsDataOccupancy.NoActivity;
import DatabaseSystem.UnitsData.UnitsDataUnitStatus;
import FrameSystem.SLibrary.SComponents.SPanel;
import java.awt.Color;

/**
 *
 * @author SPPR-LOQ
 */
public class ObjectUnitHighlight extends SPanel{

    /**
     * Creates new form ObjectUnitOccupancy
     */
    public ObjectUnitHighlight(){
        initComponents();
    }
    
    public void setOccupancy(UnitsDataOccupancy occupancy){
        sLabel1.setText(occupancy.getStringName());
        
        // Default Colors (Neutral Gray)
        Color bgColor = new Color(200, 200, 200);
        
        switch(occupancy){
            case Null, Inventory, NoActivity -> {
                bgColor = new Color(148, 163, 184);  // Slate Gray Border
            }
            case Owner, OwnerWeekenders, OwnerNoActivity -> {
                bgColor = new Color(85, 174, 245);   // Blue Border
            }
            case Tenant, TenantWeekenders, TenantNoActivity -> {
                bgColor = new Color(255,153,51);     // Orange Border
            }
            case UnturnedOver -> {
                bgColor = new Color(248, 113, 113);  // Red Border
            }
        }
        
        sPanel2.setDefaultBackgroundColor(bgColor);
        sPanel1.repaint();
    }
    
    public void setUnitStatus(UnitsDataUnitStatus unitStatus){
        sLabel1.setText(unitStatus.getStringName());
        
        // Default Colors (Neutral Gray)
        Color bgColor = new Color(200, 200, 200);
        
        switch(unitStatus){
            case Null, Inventory -> {
                bgColor = new Color(148, 163, 184);  // Slate Gray Border
            }
            case TurnedOver -> {
                bgColor = new Color(74, 222, 128);   // Green Border
            }
            case UnturnedOver -> {
                bgColor = new Color(248, 113, 113);  // Red Border
            }
        }
        
        sPanel2.setDefaultBackgroundColor(bgColor);
        sPanel1.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sPanel1 = new FrameSystem.SLibrary.SComponents.SPanel();
        sLabel1 = new FrameSystem.SLibrary.SComponents.SLabel();
        sPanel2 = new FrameSystem.SLibrary.SComponents.SPanel();

        setPaintBackground(false);
        setMaximumSize(new java.awt.Dimension(90, 50));
        setMinimumSize(new java.awt.Dimension(90, 50));
        setPreferredSize(new java.awt.Dimension(90, 50));

        sPanel1.setBorderColor(new java.awt.Color(230, 230, 230));
        sPanel1.setBorderLine(2);
        sPanel1.setDefaultBackgroundColor(new java.awt.Color(250, 250, 250));
        sPanel1.setRadius(10);
        sPanel1.setRounded(true);

        sLabel1.setForeground(new java.awt.Color(70, 70, 70));
        sLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sLabel1.setText("Owner");

        sPanel2.setDefaultBackgroundColor(new java.awt.Color(255, 153, 51));
        sPanel2.setRadius(5);
        sPanel2.setRounded(true);
        sPanel2.setMaximumSize(new java.awt.Dimension(8, 8));
        sPanel2.setMinimumSize(new java.awt.Dimension(8, 8));
        sPanel2.setName(""); // NOI18N
        sPanel2.setPreferredSize(new java.awt.Dimension(8, 8));

        javax.swing.GroupLayout sPanel2Layout = new javax.swing.GroupLayout(sPanel2);
        sPanel2.setLayout(sPanel2Layout);
        sPanel2Layout.setHorizontalGroup(
            sPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        sPanel2Layout.setVerticalGroup(
            sPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sPanel1Layout = new javax.swing.GroupLayout(sPanel1);
        sPanel1.setLayout(sPanel1Layout);
        sPanel1Layout.setHorizontalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(sLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        sPanel1Layout.setVerticalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(sPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public FrameSystem.SLibrary.SComponents.SLabel sLabel1;
    public FrameSystem.SLibrary.SComponents.SPanel sPanel1;
    private FrameSystem.SLibrary.SComponents.SPanel sPanel2;
    // End of variables declaration//GEN-END:variables
}
